### ISSUE TITLE
Stops booting if install linux-lts or linux packages

### ISSUE THREAD

**Issue by ValentinChirikov** [manjaro-arm/opi-3b-images#3]
Hello ! First of all thanks for the support of opi 3b ! 

Install wen smoothly, but after installing linux or linux-lts packages the systems stops booting

**Comment by CovLinuxGuy** [comment]
Heya

Have you managed to return your machine to a working state, and does the image support the wifi and bluetooth on the board and also does it see the emmc for install/storage purposes? 

Thank you in advance for any assist you may be able to provide :-)

**Comment by ValentinChirikov** [comment]
> Heya
> 
> Have you managed to return your machine to a working state, and does the image support the wifi and bluetooth on the board and also does it see the emmc for install/storage purposes?
> 
> Thank you in advance for any assist you may be able to provide :-)

Hello, i switched for now to armbian - seems it works quite fine, will test manjaro again next month, seems distro had some updates recently
